/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "primary-fixed-dim": "#ffb4ab",
        "inverse-primary": "#ffb4ab",
        "on-secondary-fixed-variant": "#4b473a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#dd847a",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "inverse-surface": "#303030",
        "on-secondary-fixed": "#1e1b11",
        "surface-container-high": "#eae7e7",
        "surface": "#fcf9f8",
        "surface-tint": "#934841",
        "on-tertiary-fixed": "#351002",
        "on-secondary-container": "#696457",
        "on-primary-fixed-variant": "#76322b",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "outline": "#877270",
        "tertiary-fixed": "#ffdbce",
        "surface-container-low": "#f6f3f2",
        "secondary-fixed-dim": "#cdc6b6",
        "on-surface": "#1b1c1c",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#fcb69a",
        "surface-variant": "#e4e2e1",
        "on-tertiary-container": "#cd8d73",
        "inverse-on-surface": "#f3f0f0",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#5d1f1a",
        "surface-bright": "#fcf9f8",
        "secondary": "#635e51",
        "on-surface-variant": "#544341",
        "background": "#fcf9f8",
        "surface-container-highest": "#e4e2e1",
        "tertiary": "#391303",
        "surface-container": "#f0eded",
        "tertiary-container": "#532814",
        "primary": "#410a07",
        "secondary-container": "#e9e2d1",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdad6",
        "on-background": "#1b1c1c",
        "secondary-fixed": "#e9e2d1",
        "outline-variant": "#d9c1be",
        "on-primary-fixed": "#3c0705",
        "on-tertiary-fixed-variant": "#6a3a25"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "24px",
        "margin": "32px",
        "lg": "48px",
        "gutter": "24px",
        "sm": "12px",
        "base": "8px",
        "xs": "4px",
        "xl": "80px"
      },
      "fontFamily": {
        "h1": ["Space Grotesk", "sans-serif"],
        "h2": ["Space Grotesk", "sans-serif"],
        "h3": ["Space Grotesk", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "data-mono": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"]
      },
      "fontSize": {
        "h1": ["48px", { "lineHeight": "1.1", "fontWeight": "700" }],
        "h2": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "h3": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "letterSpacing": "0.05em", "fontWeight": "700" }],
        "data-mono": ["14px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
